services:
  postgres:
    container_name: lapin_postgres 
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  rabbit:
    container_name: lapin_rabbitmq
    image: 'bitnami/rabbitmq:3.12.6'
    environment:
      - RABBITMQ_PLUGINS=rabbitmq_management rabbitmq_delayed_message_exchange
    volumes:
      - ./rabbitmq/rabbitmq_delayed_message_exchange-3.12.0.ez:/opt/bitnami/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD", "rabbitmqctl", "status"]
    ports:
      - "15672:15672"
      - "5672:5672"

